# Generated by Django 6.0 on 2025-12-30 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='User ID from userservice')),
                ('user_full_name', models.CharField(max_length=255)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leads_team', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teamapi.team')),
            ],
            options={
                'verbose_name': 'team user',
                'verbose_name_plural': 'team users',
                'ordering': ['-joined_date'],
                'unique_together': {('team', 'user_id')},
            },
        ),
    ]
