# Generated by Django 6.0 on 2025-12-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('TEAM_LEADER', 'Team Leader'), ('ADMIN', 'Admin')], default='MEMBER', max_length=20),
        ),
    ]
