# Generated by Django 6.0 on 2025-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
